Traducir es6-syntax.mdUpdate es6-syntax.md
Awoocado/guide pull request #10
Opened 2021-08-15 10:39 UTC by Vic0005

**Please describe the changes this PR makes and why it should be merged:**

2021-08-15 19:09 UTC, Vic0005 commented
Porfa @Awoocado di algo

2021-08-15 19:12 UTC, Awoocado commented
> Porfa @Awoocado di algo

Te llegué a mencionar los errores que tenias
Código lleva tilde y escribiste "El `const` palabra clave"

2021-08-15 22:53 UTC, NotKirzu requested changes
Hay muchísimos errores más. Ortográficos y con bloques de códigos. Solamente hay que cambiar los textos, no los nombres de las propiedades/métodos. Por ejemplo: `interaction.guild.nombre` no existe, déjalo como está. (`interaction.guild.name`).

Recomiendo rehacer todo sin eliminar espacios en blancos (Si existen es porque se necesitan), sin modificar los nombres de las propiedades y métodos, y revisar si se debe traducir, y si no, dejarlo como está.

2021-08-15 22:58 UTC, merged

2021-08-16 09:50 UTC, Vic0005 commented
> Hay muchísimos errores más. Ortográficos y con bloques de códigos. Solamente hay que cambiar los textos, no los nombres de las propiedades/métodos. Por ejemplo: `interaction.guild.nombre` no existe, déjalo como está. (`interaction.guild.name`).
> 
> Recomiendo rehacer todo sin eliminar espacios en blancos (Si existen es porque se necesitan), sin modificar los nombres de las propiedades y métodos, y revisar si se debe traducir, y si no, dejarlo como está.

nimodo

2021-08-16 09:52 UTC, Vic0005 commented on guide/additional-info/es6-syntax.md
> +### Literales de plantilla contra concatenación de cadenas de texto
¿En serio alguien dice "Literales de plantilla"?