Archivo traducido
Awoocado/guide pull request #7
Opened 2021-08-13 19:55 UTC by Dymidless

**Please describe the changes this PR makes and why it should be merged:**

2021-08-13 20:23 UTC, NotKirzu requested changes
`Webhook` es un nombre femenino, por tanto, se usa `las`/`una` en vez de `los`/`un` para referirse a ellas.

2021-08-13 20:23 UTC, NotKirzu commented on guide/popular-topics/webhooks.md
> +La búsqueda de webhook siempre hará uso de colecciones y promesas. Si no comprendes ninguno de los conceptos, revisalos y luego vuelve a esta sección. Puedes leer esto sobre colecciónes [Aquí](/addit
```suggestion
La búsqueda de webhooks siempre hará uso de colecciones y promesas. Si no comprendes ninguno de los conceptos, revísalos y luego vuelve a esta sección. Puedes leer sobre colecciones [aquí](/additional-info/collections.md), y  sobre promesas [aquí](/additional-info/async-await.md) y [aquí](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises).
```

2021-08-13 20:23 UTC, NotKirzu commented on guide/popular-topics/webhooks.md
> +Los webhooks pueden enviar mensajes a un canal de texto sin tener que iniciar sesión como bot. También pueden buscar, editar y eliminar sus propios mensajes. Hay una variedad de métodos en discord.js
```suggestion
Las webhooks pueden enviar mensajes a un canal de texto sin tener que iniciar sesión como bot. También pueden buscar, editar y eliminar sus propios mensajes. Hay una variedad de métodos en discord.js para interactuar con webhooks. En esta sección, aprenderás a crear, buscar, editar y utilizar webhooks.
```

2021-08-13 20:23 UTC, NotKirzu commented on guide/popular-topics/webhooks.md
> +Si quieres obbtener el objeto webhook que envió el mensaje, puedes usar <DocsLink path="class/Message?scrollTo=fetchWebhook">`Message#fetchWebhook`</DocsLink>.
```suggestion
Si quieres obtener el objeto `Webhook` que envió el mensaje, puedes usar el método <DocsLink path="class/Message?scrollTo=fetchWebhook">`Message#fetchWebhook`</DocsLink>.
```

2021-08-13 20:23 UTC, NotKirzu commented on guide/popular-topics/webhooks.md
> +Puedes editar Webhooks y WebhookClients para cambiar su nombre, avatar y canal usando <DocsLink path="class/Webhook?scrollTo=edit">`Webhook#edit()`</DocsLink>.
```suggestion
Puedes editar `Webhook`s y `WebhookClient`s para cambiar su nombre, avatar y canal usando <DocsLink path="class/Webhook?scrollTo=edit">`Webhook#edit()`</DocsLink>.
```

2021-08-13 20:23 UTC, NotKirzu commented on guide/popular-topics/webhooks.md
> +Los webhooks, como los bots, pueden enviar hasta 10 incrustaciones por mensaje. También pueden enviar archivos adjuntos y contenido normal. El <DocsLink path="class/Webhook?scrollTo=send">`Webhook#se
```suggestion
Los webhooks, como los bots, pueden enviar hasta 10 incrustaciones por mensaje. También pueden enviar archivos adjuntos y contenido normal. El método <DocsLink path="class/Webhook?scrollTo=send">`Webhook#send()`</DocsLink> utilizado para enviar a una webhook es muy similar al método utilizado para enviar a un canal de texto. Los webhooks también pueden elegir cómo aparecerá el nombre de usuario y el avatar cuando envíen el mensaje.
```

2021-08-13 20:23 UTC, NotKirzu commented on guide/popular-topics/webhooks.md
> +Puedes usar <DocsLink path="class/Webhook?scrollTo=fetchMessage">`Webhook#fetchMessage()`</DocsLink> para recuperar mensajes enviados previamente por el Webhook.
```suggestion
Puedes usar <DocsLink path="class/Webhook?scrollTo=fetchMessage">`Webhook#fetchMessage()`</DocsLink> para obtener mensajes enviados previamente por el Webhook.
```

2021-08-14 18:55 UTC, merged

2021-08-14 18:56 UTC, Awoocado commented
Garcias @NotKirzu por la revisión 🤝